### ISSUE TITLE
Missing steps in readme

### ISSUE THREAD

**Issue by zenmetsu** [VPraharsha03/GentooWSL2#2]
Hello!

I noticed that the readme never calls out installing sudo or adding the non-root user to sudo.  This, combined with not setting password for the root user, creates a condition where the user will be unable to obtain administrative privileges upon logging out for the first time.

Additionally, the step to update the gentoo repo to use git does not call out which file to edit, which might be helpful for a new user.

**Comment by VPraharsha03** [comment]
@zenmetsu I've updated the README with instructions to install sudo and for the rest of the things
